[project]
name = "simforge-api"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "pydantic-settings",
  "redis",
  "rq"
]

[tool.uvicorn]
factory = false
reload = true
host = "0.0.0.0"
port = 8000

