[project]
name = "simforge-api"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.115,<0.116",
  "uvicorn>=0.30,<0.31",
  "pydantic>=2.8,<3.0"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
