name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m pip install --upgrade pip
      - run: pip install -e .
        continue-on-error: true
      - run: pip install fastapi uvicorn[standard] pydantic-settings
      - run: python -c "import fastapi; print('API ok')"

  worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/worker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: python -m pip install --upgrade pip
      - run: pip install -e .
        continue-on-error: true
      - run: pip install rq redis pydantic
      - run: python -c "import rq, redis; print('Worker ok')"

  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile || pnpm install
      - run: pnpm build

